### ISSUE TITLE
Invalid error from example code

### ISSUE THREAD

**Issue by vizor21** [95th/jsmn-rs#1]
I ran the example, parse.rs with no changes and it panicked.

     Running `target/debug/test_jsmn`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Invalid', src/main.rs:8:32
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
     . . .

I should mention that I didn't clone this repository, I just added 'jsmn = "0.1.4"' to my Cargo.toml file.  I'm not a Rust expert so perhaps there is a discrepancy.

I also notice that if I run the tests, "cargo test -p jsmn", all the tests run except for "parse_array_02", which has the same JSON string as the example.

**Comment by 95th** [comment]
Hi.. Thanks for opening the issue. It seems I didn't publish the latest code on crates.io.

I have now published the new version 0.1.5. Please give it a try and let me know if you still have issues.

**Comment by vizor21** [comment]
> Hi.. Thanks for opening the issue. It seems I didn't publish the latest code on crates.io.
> 
> I have now published the new version 0.1.5. Please give it a try and let me know if you still have issues.

Fantastic!  It works now.  BTW, is there some way to determine how many tokens need to be allocated?  I saw in the C API that if you pass a null as the token array you get back the number of tokens needed.  I didn't see any way to do that in Rust.

Thanks again!
